DavidRisch/crossing_consoles

src/CMakeLists.txt, src/Game/Player.cpp, src/Game/Player.h, src/Game/Position.cpp, src/Game/Position.h, src/Game/Wall.cpp, src/Game/Wall.h, src/Game/World.cpp, src/Game/World.h
=> Add game interfaces

src/CMakeLists.txt, src/communication/ClientCommunication.cpp, src/communication/ServerCommunication.cpp, src/communication/messages/ConnectionRequestMessage.cpp, src/communication/messages/ConnectionRequestMessage.h, src/communication/messages/ConnectionResponseMessage.cpp, src/communication/messages/ConnectionResponseMessage.h, src/communication/messages/KeepAliveMessage.cpp, src/communication/messages/KeepAliveMessage.h, src/communication/messages/Message.cpp, src/communication/messages/Message.h, src/communication/messages/MessageCoder.cpp, src/communication/messages/MessageCoder.h, src/communication/messages/PayloadMessage.cpp, src/communication/messages/PayloadMessage.h, tests/CMakeLists.txt, tests/message_coder.cpp
=> Message coder

src/communication/crc/CRCHandler.cpp, src/communication/crc/CRCHandler.h, src/communication/messages/MessageCoder.cpp, src/communication/messages/MessageCoder.h, tests/crc_handler.cpp, tests/message_coder.cpp
=> Integrate crc

src/CMakeLists.txt, src/communication/ProtocolDefinition.h, src/communication/connection_layer/Connection.cpp, src/communication/connection_layer/Connection.h, src/communication/low_level/ByteStream.h, src/communication/low_level/IInputStream.h, src/communication/low_level/IOutputStream.h, src/communication/low_level/MockBidirectionalByteStream.cpp, src/communication/low_level/MockBidirectionalByteStream.h, src/communication/low_level/MockInputStream.cpp, src/communication/low_level/MockInputStream.h, src/communication/message_layer/MessageInputStream.cpp, src/communication/message_layer/MessageInputStream.h, src/communication/message_layer/MessageOutputStream.cpp, src/communication/message_layer/MessageOutputStream.h, src/communication/messages/ConnectionRequestMessage.h, src/communication/messages/MessageCoder.cpp, src/communication/messages/MessageCoder.h, tests/CMakeLists.txt, tests/connection.cpp, tests/message_coder.cpp, tests/message_stream.cpp, tests/mocks.cpp
=> Connection

src/communication/message_layer/crc/CRCHandler.cpp, src/communication/message_layer/crc/CRCHandler.h, src/communication/message_layer/message_stream/MessageCoder.cpp, tests/crc_handler.cpp
=> Crc bytestream

src/communication/ProtocolDefinition.h, src/communication/message_layer/message_stream/MessageCoder.cpp, src/communication/message_layer/message_stream/MessageCoder.h, src/communication/message_layer/message_stream/MessageInputStream.cpp, tests/message_coder.cpp
=> Add flag and escape sequence to MessageCoder

src/CMakeLists.txt, src/communication/ProtocolDefinition.h, src/communication/byte_layer/byte_stream/IInputByteStream.h, src/communication/byte_layer/byte_stream/MockBidirectionalByteStream.cpp, src/communication/byte_layer/byte_stream/MockBidirectionalByteStream.h, src/communication/byte_layer/byte_stream/MockInputStream.h, src/communication/byte_layer/byte_stream/SocketByteStream.cpp, src/communication/byte_layer/byte_stream/SocketByteStream.h, src/communication/connection_layer/Connection.cpp, src/communication/connection_layer/Connection.h, src/communication/message_layer/message/AcknowledgeMessage.cpp, src/communication/message_layer/message/AcknowledgeMessage.h, src/communication/message_layer/message/ConnectionRequestMessage.cpp, src/communication/message_layer/message/ConnectionRequestMessage.h, src/communication/message_layer/message/ConnectionResponseMessage.cpp, src/communication/message_layer/message/ConnectionResponseMessage.h, src/communication/message_layer/message/KeepAliveMessage.cpp, src/communication/message_layer/message/KeepAliveMessage.h, src/communication/message_layer/message/Message.cpp, src/communication/message_layer/message/Message.h, src/communication/message_layer/message/PayloadMessage.cpp, src/communication/message_layer/message/PayloadMessage.h, src/communication/message_layer/message_stream/MessageCoder.cpp, src/communication/message_layer/message_stream/MessageInputStream.cpp, src/communication/message_layer/message_stream/MessageInputStream.h, tests/byte_stream.cpp, tests/connection.cpp, tests/message_coder.cpp, tests/message_stream.cpp
=> Acknowledge

src/game/Compositor.h, src/game/terminal/RealTerminal.cpp, src/game/terminal/RealTerminal.h
=> Fix Windows terminal output and add console enhancement

src/CMakeLists.txt, src/game/GameClient.cpp, src/game/GameClient.h, src/game/GameServer.cpp, src/game/GameServer.h, src/game/World.cpp, src/game/World.h, src/game/WorldGenerator.cpp, src/game/WorldGenerator.h, src/game/networking/Change.cpp, src/game/networking/Change.h, src/main_client.cpp, src/main_server.cpp, tests/CMakeLists.txt, tests/game.cpp, tests/game_networking.cpp
=> Game basic communication

src/game/GameClient.cpp, src/game/world/World.cpp, tests/CMakeLists.txt, tests/player.cpp, tests/position.cpp, tests/renderer.cpp, tests/sprite.cpp, tests/wall.cpp, tests/world.cpp
=> Game tests

src/communication/message_layer/message_stream/MessageCoder.cpp, tests/connection_manager.cpp, tests/message_coder.cpp
=> Fix crc calculation and add tests

src/communication/connection_layer/connection/ClientSideConnectionManager.cpp, src/communication/connection_layer/connection/ClientSideConnectionManager.h, src/communication/connection_layer/connection/Connection.cpp, src/communication/connection_layer/connection/ConnectionManager.cpp, src/communication/connection_layer/connection/ConnectionManager.h, src/game/GameClient.cpp, tests/connection_manager.cpp
=> Client connection manager

src/game/GameClient.cpp, src/game/GameClient.h, src/game/GameServer.cpp, src/game/common/Position.h, src/game/networking/ISerializable.h, src/game/visual/Renderer.cpp, src/game/world/World.cpp, src/game/world/World.h, src/main_client.cpp, tests/game.cpp, tests/game_networking.cpp, tests/game_serialization.cpp, tests/world.cpp
=> Fix memory leak in World

src/CMakeLists.txt, src/communication/connection_layer/connection/ClientSideConnectionManager.cpp, src/game/GameClient.cpp, src/game/GameClient.h, src/game/GameDefinition.h, src/game/GameServer.cpp, src/game/GameServer.h, src/game/networking/Change.h, src/game/terminal/MockTerminal.cpp, src/game/terminal/MockTerminal.h, src/game/visual/Renderer.cpp, src/game/visual/Renderer.h, src/game/world/Player.cpp, src/game/world/Player.h, src/game/world/Spawner.cpp, src/game/world/Spawner.h, src/game/world/World.cpp, src/game/world/World.h, tests/CMakeLists.txt, tests/game_networking.cpp, tests/spawner.cpp
=> Game multiple players

src/communication/connection_layer/connection/Connection.cpp, src/communication/connection_layer/connection/Connection.h, src/communication/connection_layer/connection/ConnectionManager.cpp, src/communication/connection_layer/connection/ConnectionManager.h, tests/connection.cpp, tests/connection_manager.cpp
=> Close connection

src/communication/ProtocolDefinition.h, src/communication/connection_layer/connection/ConnectionManager.cpp, src/communication/connection_layer/connection/ConnectionManager.h, tests/connection_manager.cpp
=> Send KeepAlive Messages to prevent timeouts

src/CMakeLists.txt, src/communication/byte_layer/byte_stream/SocketByteServer.cpp, src/communication/byte_layer/byte_stream/SocketByteServer.h, src/communication/byte_layer/byte_stream/SocketByteStream.cpp, src/communication/byte_layer/byte_stream/SocketByteStream.h, src/communication/byte_layer/connection_simulator/ConnectionSimulatorFlaky.cpp, src/communication/byte_layer/connection_simulator/ConnectionSimulatorFlaky.h, src/communication/byte_layer/connection_simulator/ConnectionSimulatorPerfect.cpp, src/communication/byte_layer/connection_simulator/ConnectionSimulatorPerfect.h, src/communication/byte_layer/connection_simulator/IConnectionSimulatorProvider.h, src/communication/byte_layer/connection_simulator/PerfectConnectionSimulatorProvider.cpp, src/communication/byte_layer/connection_simulator/PerfectConnectionSimulatorProvider.h, src/communication/connection_layer/connection/ClientSideConnectionManager.cpp, src/communication/connection_layer/connection/ClientSideConnectionManager.h, src/communication/connection_layer/connection/ConnectionManager.cpp, src/communication/connection_layer/connection/ConnectionManager.h, src/communication/connection_layer/connection/ServerSideConnectionManager.cpp, src/communication/connection_layer/connection/ServerSideConnectionManager.h, tests/CMakeLists.txt, tests/connection_manager.cpp, tests/connection_simulator.cpp, tests/fixtures/ConnectionManagers.h, tests/fixtures/FlakyConnectionManagers.h, tests/flaky_connection.cpp
This is a part of but does not fix #86
=> Add Robust communication tests

tests/mocks.cpp
=> Add test for MockInputStream class

src/CMakeLists.txt, src/communication/ProtocolDefinition.h, src/game/GameClient.cpp, src/game/GameClient.h, src/game/GameServer.cpp, src/game/networking/SerializationUtils.cpp, src/game/networking/SerializationUtils.h, src/game/visual/ColoredCharMatrix.cpp, src/game/visual/ColoredCharMatrix.h, src/game/visual/Compositor.cpp, src/game/visual/Compositor.h, src/game/visual/PlayerList.cpp, src/game/visual/PlayerList.h, src/game/visual/symbols.h, src/game/world/Player.cpp, src/game/world/Player.h, src/game/world/World.h, src/main_server.cpp, tests/CMakeLists.txt, tests/colored_string_matrix.cpp, tests/connection_manager.cpp, tests/fixtures/ConnectionManagers.h, tests/fixtures/GamePlayerList.h, tests/game_networking.cpp, tests/game_player_list.cpp, tests/game_serialization.cpp
Fix #87 
Due to issue #103 commits e32265a7 and f479e0ca were necessary for this to run.
=> Player list

src/CMakeLists.txt, src/game/terminal/RealTerminal.cpp, src/game/visual/Compositor.cpp, src/game/visual/HealthDisplay.cpp, src/game/visual/HealthDisplay.h, src/game/visual/PlayerList.cpp
=> Health display

src/CMakeLists.txt, src/game/GameClient.cpp, src/game/GameClient.h, src/game/GameDefinition.h, src/game/GameLogic.cpp, src/game/GameLogic.h, src/game/GameServer.cpp, src/game/GameServer.h, src/game/networking/Change.h, src/game/networking/ISerializable.h, src/game/visual/Renderer.cpp, src/game/visual/Renderer.h, src/game/world/Player.cpp, src/game/world/Player.h, src/game/world/Projectile.cpp, src/game/world/Projectile.h, src/game/world/World.cpp, src/game/world/World.h, src/game/world/items/Weapon.cpp, src/game/world/items/Weapon.h, tests/CMakeLists.txt, tests/fixtures/GamePlay.cpp, tests/fixtures/GamePlay.h, tests/game.cpp, tests/game_logic.cpp, tests/game_projectile.cpp, tests/game_serialization.cpp, tests/player.cpp, tests/renderer.cpp, tests/world.cpp
=> Shoot projectile

src/game/GameLogic.cpp, src/game/GameLogic.h, src/game/visual/Compositor.cpp, src/game/visual/PlayerList.cpp, src/game/visual/PlayerList.h, src/game/world/Player.cpp, src/game/world/Player.h, tests/game_logic.cpp, tests/game_serialization.cpp
=> Game implement score

src/game/GameLogic.cpp, src/game/world/Player.cpp, src/game/world/Player.h, tests/game_logic.cpp, tests/game_serialization.cpp
=> Change player direction according to player movement

src/game/terminal/RealTerminal.cpp, src/game/terminal/RealTerminal.h
=> Add clearing of terminal if its size has changed on Linux

src/communication/connection_layer/connection/ClientSideConnectionManager.cpp, src/communication/connection_layer/connection/ClientSideConnectionManager.h, src/game/GameClient.cpp, src/game/GameClient.h, src/game/GameServer.cpp, src/game/world/World.cpp, src/game/world/World.h, src/main_client.cpp, tests/game_networking.cpp
=> Game disconnect

src/game/GameClient.cpp, src/game/GameDefinition.h, src/game/GameServer.cpp, src/game/networking/Change.cpp, src/game/networking/Change.h, src/game/networking/SerializationUtils.cpp, src/game/networking/SerializationUtils.h, src/game/visual/ColoredCharMatrix.cpp, src/game/visual/ColoredCharMatrix.h, src/game/visual/PlayerList.cpp, src/game/visual/PlayerList.h, src/game/visual/Renderer.cpp, src/game/visual/symbols.h, src/game/world/Player.cpp, src/game/world/Player.h, src/main_client.cpp, tests/game_serialization.cpp
=> Custom player color

src/communication/ProtocolDefinition.h, tests/CMakeLists.txt, tests/connection_manager.cpp, tests/fixtures/ConnectionManagers.h, tests/fixtures/FlakyConnectionManagers.h, tests/game_networking.cpp, tests/utils/TimingHelper.cpp, tests/utils/TimingHelper.h
=> Tests timing

src/game/visual/Compositor.cpp, src/game/visual/Compositor.h, src/game/visual/symbols.h, tests/game.cpp, tests/game_player_list.cpp
=> Render title

src/game/visual/Renderer.cpp
=> Fix rendering issues

doc/doxygen/markdown/game.md, doc/doxygen/markdown/game_client_server.md, doc/doxygen/markdown/game_player_controls.md, doc/doxygen/markdown/game_world_rules.md, doc/doxygen/markdown/mainpage.md, doc/doxygen/markdown/putty.md, doc/doxygen/markdown/ssh.md
=> Update game documentation

src/communication/connection_layer/connection/statistics/ConnectionStatistics.cpp, src/communication/connection_layer/connection/statistics/ConnectionStatistics.h, src/communication/connection_layer/connection/statistics/StatisticPrinter.cpp, src/game/GameServer.cpp, tests/statistics.cpp
=> Calculate average response time incrementally

doc/doxygen/markdown/game_player_controls.md, src/CMakeLists.txt, src/communication/connection_layer/connection/statistics/StatisticPrinter.h, src/game/GameClient.cpp, src/game/GameClient.h, src/game/visual/Compositor.cpp, src/game/visual/Compositor.h, src/game/visual/PlayerList.cpp, src/game/visual/PlayerList.h, src/game/visual/StatisticsTable.cpp, src/game/visual/StatisticsTable.h, src/game/visual/Table.cpp, src/game/visual/Table.h
=> Show statistics

doc/doxygen/markdown/game_client_server.md, src/game/GameClient.cpp, src/game/GameClient.h, src/game/GameServer.cpp, src/game/networking/Change.h, src/game/world/World.cpp, src/game/world/World.h, src/main_server.cpp
=> Fast world update

src/communication/connection_layer/connection/Connection.cpp, src/communication/connection_layer/connection/Connection.h, src/communication/connection_layer/connection/ConnectionManager.cpp, src/game/GameClient.cpp, src/game/GameServer.cpp, src/game/GameServer.h
=> Restrict player count

src/game/visual/Compositor.cpp, src/game/visual/Compositor.h
=> Draw box around respawn message

src/game/visual/Compositor.cpp, src/game/visual/Compositor.h
=> Add play instructions in footer

src/game/GameClient.cpp, src/game/GameClient.h, src/game/GameDefinition.h, src/game/GameLogic.cpp, src/game/GameLogic.h, src/game/GameServer.cpp, src/game/GameServer.h, tests/game_networking.cpp, tests/utils/TestGameDefinition.h
=> Make respawn time adaptable for testing

src/CMakeLists.txt, src/game/GameDefinition.h, src/game/GameLogic.cpp, src/game/GameLogic.h, src/game/GameServer.cpp, src/game/visual/ColoredCharMatrix.cpp, src/game/visual/ColoredCharMatrix.h, src/game/visual/Renderer.cpp, src/game/world/ColoredField.cpp, src/game/world/ColoredField.h, src/game/world/World.cpp, src/game/world/World.h, tests/CMakeLists.txt, tests/colored_fields.cpp, tests/game_logic.cpp, tests/game_serialization.cpp, tests/world.cpp
=> Show item damage in color

doc/doxygen/markdown/ssh.md, src/main_client.cpp
=> Input validation

CMakeLists.txt, src/communication/byte_layer/byte_stream/SocketByteServer.cpp, src/communication/byte_layer/byte_stream/SocketByteStream.cpp, src/communication/byte_layer/byte_stream/socket_libs.h, src/communication/connection_layer/connection/ClientSideConnectionManager.cpp, src/communication/connection_layer/connection/ClientSideConnectionManager.h, src/communication/connection_layer/connection/Connection.cpp, src/communication/connection_layer/connection/Connection.h, src/communication/connection_layer/connection/ConnectionManager.cpp, src/communication/connection_layer/connection/ConnectionManager.h, src/communication/connection_layer/connection/ServerSideConnectionManager.cpp, src/communication/connection_layer/connection/ServerSideConnectionManager.h, src/game/GameClient.cpp, src/game/GameClient.h, src/game/GameServer.cpp, src/game/GameServer.h, src/game/networking/ISerializable.h, src/game/visual/ColoredCharMatrix.cpp, src/game/visual/ColoredCharMatrix.h, src/game/visual/Compositor.cpp, src/game/visual/Compositor.h, src/game/world/RandomWorldGenerator.cpp, src/game/world/RandomWorldGenerator.h, src/game/world/World.cpp, src/main_server.cpp, tests/game_networking.cpp
=> Improve performance 2

src/game/visual/Renderer.cpp, src/game/visual/symbols.h, src/game/world/block_types.h
=> Add player sprites for each direction

doc/doxygen/markdown/game_world_generator.md, src/game/common/Color.cpp, src/game/common/Color.h, src/game/visual/Renderer.cpp, src/game/world/RandomWorldGenerator.cpp, src/game/world/RandomWorldGenerator.h
=> Dynamic world generation

src/game/world/RandomWorldGenerator.cpp, src/game/world/RandomWorldGenerator.h
=> World generation smooth edges

src/game/visual/Renderer.cpp, src/game/world/block_types.h
=> Add dead player sprite

src/game/world/Spawner.cpp, src/game/world/Spawner.h, src/game/world/World.h, src/game/world/items/ItemGenerator.cpp, src/game/world/items/ItemGenerator.h
=> Implement random spawner

src/communication/ProtocolDefinition.h, src/communication/byte_layer/byte_stream/SocketByteServer.cpp, src/communication/byte_layer/byte_stream/SocketByteStream.cpp, src/communication/byte_layer/byte_stream/socket_libs.h
=> Improve unix socket

src/CMakeLists.txt, src/communication/ProtocolDefinition.h, src/communication/byte_layer/byte_stream/SocketByteServer.cpp, src/communication/byte_layer/byte_stream/SocketByteStream.cpp, src/communication/message_layer/message_stream/MessageCoder.cpp, src/game/GameClient.cpp, src/game/GameClient.h, src/game/GameServer.cpp, src/game/GameServer.h, src/game/terminal/RealTerminal.cpp, src/game/world/RandomWorldGenerator.cpp, src/game/world/World.cpp, src/game/world/World.h, src/main_client.cpp, src/main_server.cpp, tests/connection_manager.cpp, tests/game_networking.cpp
=> Improve performance 3

src/game/world/items/Gun.cpp, src/game/world/items/Heart.cpp, src/game/world/items/Points.cpp, src/game/world/items/Sword.cpp
=> Center item sprites

src/CMakeLists.txt, src/game/visual/Renderer.cpp, src/game/visual/Renderer.h, src/game/visual/SpriteGenerator.cpp, src/game/visual/SpriteGenerator.h, src/game/visual/SpriteMap.cpp, tests/game_player_list.cpp, tests/sprite_map.cpp
=> Refactor renderer

src/game/terminal/RealTerminal.cpp, src/game/terminal/RealTerminal.h
=> Improve efficiency of RealTerminal.SetScreen()

src/game/GameClient.cpp, src/game/GameClient.h, src/game/networking/Change.cpp, src/game/networking/Change.h, tests/game_networking.cpp
=> Game key frequency

src/game/world/Spawner.cpp, src/game/world/Spawner.h
=> Implement better random spawns
